### PR TITLE
Rebase my fork to current 3.3 main

### PR DESCRIPTION
**Pull request by mikeiimura**
I want to rebase my fork so that I can resume working on the RAV4 EV port and use the new 4G modem.

### CODE REVIEW

**Review by mikeiimura — COMMENTED** [review]
No substantive conflicts found

**Comment by mikeiimura** [comment]
@dexterbg I am such a newbie. Why can't I just push this merge through? It says I can't approve my own pull request within my own fork.

**Comment by dexterbg** [comment]
Mike, not sure what you did here. A pull request for your own fork doesn't make any sense. A pull request tells another repository maintainer that you ask them to merge your changes into their repository.

To rebase your changes & repository to the latest upstream status, you first pull all changes from upstream locally, then merge or rebase your local branch(es) to a clean resolution of conflicts, then push into your github repository.

If you're about to submit a patch for a pull request, you should create a dedicated branch based on the updated master, only containing your changes. Then push that branch into your github repository and submit the pull request for that branch. That way your changes are kept clean & compact & easy to read, and you can easily add more changes to that branch, which github will automatically add to the pull request (as that's defined for that branch).

Regards,
Michael

**Comment by mikeiimura** [comment]
> Mike, not sure what you did here. A pull request for your own fork doesn't make any sense. A pull request tells another repository maintainer that you ask them to merge your changes into their repository.
> 
> To rebase your changes & repository to the latest upstream status, you first pull all changes from upstream locally, then merge or rebase your local branch(es) to a clean resolution of conflicts, then push into your github repository.
> 
> If you're about to submit a patch for a pull request, you should create a dedicated branch based on the updated master, only containing your changes. Then push that branch into your github repository and submit the pull request for that branch. That way your changes are kept clean & compact & easy to read, and you can easily add more changes to that branch, which github will automatically add to the pull request (as that's defined for that branch).
> 
> Regards, Michael

Michael,

I did a "Fetch Upstream" and it had an unresolved conflict, resulting in it forcing me to do a Pull Request. I had to restore the Asset you had me remove before (with a 'git add') and go through the command line git commands recommended. I couldn't figure out how to issue the git commands on the Github.com site, so I installed GitHub Desktop and muddled through those commands to get it merged. As you can see, I seem to have resolved it by myself.

- Mike

**Pull request merged**
